Resolved Issue: 5
opencodeiiita/Contest-Countdown pull request #7
Opened 2021-10-05 19:23 UTC by adtoria

Issue: 5

#### Short description of what this resolves:
- Completed _getTimerText function to make & return a string that displays the remaining time.

#### Changes proposed in this pull request and/or Screenshots of changes:
- NA

2021-10-05 21:24 UTC, rag-hav requested changes
Need to handle edge cases properly

2021-10-05 21:24 UTC, rag-hav commented on gnome/extension.js
> -  _refreshUI: function (data) {
dont delete this function

2021-10-05 21:24 UTC, rag-hav commented on gnome/extension.js
> +    if (timeDiff >= 0) {
+infinity will be handled by this if.

Note: If you find the edge cases given by secondsTillNextContest unwieldy. You can edit them to -1 -2 -3.. or anything. Just make sure to document them properly.

2021-10-06 12:02 UTC, adtoria commented
> Need to handle edge cases properly

Made changes. Please review.

2021-10-06 13:22 UTC, rag-hav requested changes

2021-10-06 13:22 UTC, rag-hav commented on gnome/extension.js
> +        timerText = "Loading data.";
either remove the dot or make it three dots

2021-10-06 13:29 UTC, merged